# Generated by Django 5.2.8 on 2025-11-25 12:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=16, null=True)),
                ('discounted_price', models.CharField(blank=True, max_length=16, null=True)),
                ('reviews', models.CharField(blank=True, max_length=16, null=True)),
                ('image_paths', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None)),
                ('product_code', models.CharField(blank=True, max_length=32, null=True)),
                ('characteristics', models.JSONField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=32, null=True)),
                ('internal_memory', models.CharField(blank=True, max_length=16, null=True)),
                ('screen_diagonal', models.CharField(blank=True, max_length=32, null=True)),
                ('display_resolution', models.CharField(blank=True, max_length=32, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=128, null=True)),
                ('series', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
